# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('removido', models.BooleanField(default=False)),
                ('user_add', models.IntegerField()),
                ('date_add', models.DateField()),
                ('user_up', models.IntegerField(blank=True, null=True)),
                ('date_up', models.DateField(blank=True, null=True)),
                ('user_del', models.IntegerField(blank=True, null=True)),
                ('date_del', models.DateField(blank=True, null=True)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_subtipo', to='ged.Tipo')),
            ],
        ),
    ]
