# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0002_auto_20171018_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=200, verbose_name='CNPJ')),
                ('raz_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('ie', models.CharField(max_length=200, verbose_name='Inscrição Estadual')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=200, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('site', models.URLField(verbose_name='Site')),
                ('user_add', models.IntegerField()),
                ('date_add', models.DateField()),
                ('user_up', models.IntegerField(blank=True, null=True)),
                ('date_up', models.DateField(blank=True, null=True)),
                ('user_del', models.IntegerField(blank=True, null=True)),
                ('date_del', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
