# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0003_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='raz_social',
            new_name='razao_social',
        ),
    ]
