# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0006_pagina_nomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomePagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Citado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='informacoes',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='nomes',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='pagina',
            name='nomes',
        ),
        migrations.AddField(
            model_name='documento',
            name='capa',
            field=models.FileField(default='', upload_to='capas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagina',
            name='arquivo',
            field=models.FileField(upload_to='arquivos'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_tipodocumento', to='ged.Documento', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_tipodocumento', to='ged.Tipo', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='nomepagina',
            name='pagina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nome_pagina', to='ged.Pagina', verbose_name='Pagina'),
        ),
    ]
