# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0007_auto_20171109_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagina_tipo', to='ged.Tipo', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
