# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0008_auto_20171111_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='tipo',
        ),
    ]
