# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0010_auto_20171112_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_add', models.IntegerField()),
                ('date_add', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='pagina',
            name='texto',
            field=models.TextField(verbose_name='Informações'),
        ),
    ]
