# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0011_auto_20171114_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='frenteverso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frente e Verso'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='lado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lado'),
        ),
    ]
